origin-oberth-name = Oberth
origin-oberth-desc = An independent colony founded by German immigrants from old Earth and consisting of one giant hive city on a barren desert planet. It was once one of the most promising of colonies, back when the terraforming process had just begun; a group of scientists gathered together to forge a brighter future. Now, after a stalemated civil war, Oberth has degenerated into an anarcho-capitalist hell ruled by three governments, all unable to establish control over the city or stop ravaging band wars. Even Hanza and NeoTheology failed to bring order. Though still a place of infinite possibilities, most of them are illegal.

origin-predstraza-name = Predstraza
origin-predstraza-desc = The product of a widely held idea back on Earth that if one were to bring all of the Balkan populations on one colony ship, they would be forced to put aside their differences and work together to survive. Unfortunately, that idea failed miserably and is still failing. A jungle death world, full of hostile fauna and mired in endless armed conflict. The Serbian government occupied all of Predstraza's space ports and controls most of the civilized regions. Located far from Hanza or NT territories, it's a place favored for business by pirates, smugglers and all manner of outlaw.

origin-sich-prime-name = Sich Prime
origin-sich-prime-desc = A Ukrainian colony that was a major industrial center during the Corporation Wars, during which they made the fatal mistake of siding with Nanotrasen. Bombed and poisoned, this planet suffered the harshest toll of the war, both from population loss and ecological devastation. While ostensibly under the direct control of Hanza, its local military is extremely ineffective and known to support the Founders - a revanchist international group that seeks the premature destruction of Nanotrasen.

origin-new-rome-name = New Rome
origin-new-rome-desc = One of the first colonies founded by American settlers, New Rome was rich with biosphere and natural resources and served as Nanotrasen's headquarters when it was still an emerging power. As such, it holds the highest survival rate of any planet in the galaxy. Although the War ended before it was siege, New Rome suffered an economic crisis following the fall of Nanotrasen and never recovered. Formerly a garden world, it is littered with hive cities, declining ecosystems, widespread poverty... Although a former garden world, New Rome now is a hive of poverty and chaos. It offers nothing but a chance for people to join the faceless church of immense influence and work in its hierarchy or, if not, die out in the wastes.

origin-shimatengoku-name = Shimatengoku
origin-shimatengoku-desc = Founded by a Japanese megacorporation, Shimatengoku was - and still is - a high tech paradise. With 95% of its times in the air struggle, in a society based around a massive virtual presence. When the time of the Corporation War came, Shimatengoku made a judgment call to side with the Syndicate, and prospered immensely as a result. While there is local government authority is weak and corruption is rampant, the planet is mostly it's economy is controlled by Arrakis Space Works, an enormous company that is responsible for producing most of the military AI components used in Hanza. Arrakis Space Works itself is owned by a family with ties to the Yakuza, organized crime syndicates...

origin-hmss-destined-name = HMSS "Destined"
origin-hmss-destined-desc = A British colony ship that was one of all that failed to find a habitable world by the time their fuel ran out, but the crew managed to survive by turning their ship into the storm in Hanza controlled space. A rusty, metal box with rocketing costs of living, a permanent space roach infestation and no natural ecology, the Destiny is a must for an industrial roadway. The War was rather merciful to it, and the station remained neutral through most of the conflict; however, the "Destiny" was recently occupied by the Syndicate, which changed everything. They say while it was an exactly functional enough place before, the crew of the "Destiny" never got a decent life, and the chaos, the elitist title "Hell", and the certain very Baron among the ruling nobles of House Thanatos made the atmosphere on board only worse.

origin-crozet-name = Crozet
origin-crozet-desc = A lifeless, unforgiving ice world, rich with rare minerals, life on Crozet is only possible underground. It came into existence as a cryptocurrency experiment founded by the Western, industrialized laboratory cadre — later the area was crawling with badassed and mad.

origin-first-expeditionary-fleet-name = First Expeditionary Fleet
origin-first-expeditionary-fleet-desc = A collection of old and modified colony ships, FTL capable shipyards, mobile hydroponics, and a military of armed battleships. Holding the status of a de facto military for the Aegis Contract Group PMC, the armada can be deployed wherever or whenever of a contract, and if things get too hot, the fleet can even switch to deep space and never be seen again. It moves from planet to planet in Han bin, like a boot on the neck of planetary governments. For the fleet to function, a gigantic pile of manpower is needed, and the armada's ships tend to be as numerous as small cities, all of which are filled with a floating crowd of emotions civilians and military personnel. It is the crowd in the Fleet's ships that makes it the most natural breeding ground for all the dark emotions one could imagine.

origin-end-point-name = End Point
origin-end-point-desc = A trinary system with complicated orbits and black hole located in a safe distance from the world all of the habitable planets. One of the first colonised regions of space, because it is rich in resources, the whole system (which consists of more than a hundred of large celestial bodies are there) can definitely result a travel bargain. And the fact that is also an extremely important point in the world of scientific studies, due to that blackhole and the abundance of rare materials. Never one strong power controlled over the clone.

origin-nss-forecaster-name = NSS "Forecaster"
origin-nss-forecaster-desc = Designed to serve as an FTL mining platform by the first days of NanoTrasen. It was used for that, but eventually stars started coming back from Null Space, and in order to salvage the many wonders first, NanoTrasen has sent this platform into space to serve as a local headquarter, whats place that uncovered them later, by chance, those of the independent ones.

origin-eureka-name = Eureka
origin-eureka-desc = Once a perfect world for the Australian colonists, their neutrality during the corporate wars cost them the paradise. Thus did the Syndicate and Nanotrasen bomb Eureka to hell, causing once verdant lands to become frozen hellish deserts. Known today as the forgotten planet, the Eurekans are known to be eerily good trackers and pathfinders, which causes what's left of the Eurekan people to pay a tithe to Hansi and NeoTheology both in the form of criminals. All in the name of "saving what's left".

origin-tripwire-belt-name = Tripwire Belt
origin-tripwire-belt-desc = A network of hidden ships, gun emplacements and listening bases placed in a large asteroid belt during the Corporate War by the Syndicate, for the purpose of tearing the early warning station for attacks on Nova Central core worlds. After the end of the conflict, Aegis Contract Group gave them a new life as a gaming camp where the territory is overlapped on the front of old.

origin-kestrel-hive-name = Kestrel Hive
origin-kestrel-hive-desc = A massive collection of ships - mining asteroids at that point turned out to have the best conditions for the survival under the great press of all of life in the guild. It became a real town with a full changed interrepair and comfort. Tiny as they were, of them produced a special cast of "hard" miners, used to working hard, natural cast most tenants. . The ship is strictly separate status over its people: either is waiting for nothing else but the next shift, which is repeated forever.
